name: CI
on: [push]
jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm ci

      - name: Run ESLint
        run: npm run ci:lint

      - name: Run Tests:
        run: npm run ci:test
